package entity;
// Generated 12-sep-2018 18:26:09 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * UsuarioRol generated by hbm2java
 */
@Entity(name ="usuario_rol")
@Table(name = "usuario_rol", catalog = "eapro")
public class UsuarioRol implements java.io.Serializable {

	private Integer idusuarioRol;
	private Rol rol;
	private Usuario usuario;

	public UsuarioRol() {
	}

	public UsuarioRol(Rol rol, Usuario usuario) {
		this.rol = rol;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idusuario_rol", unique = true, nullable = false)
	public Integer getIdusuarioRol() {
		return this.idusuarioRol;
	}

	public void setIdusuarioRol(Integer idusuarioRol) {
		this.idusuarioRol = idusuarioRol;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_rol")
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
